######################
#RBAC
######################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-sandbox
  namespace: ${NS}
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-sandbox-token
  namespace: ${NS}
  annotations:
    kubernetes.io/service-account.name: agent-sandbox
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-sandbox
rules:
  - apiGroups:
      - "*"
    resources:
      - "pods"
      - "pods/exec"
      - "pods/log"
      - "pods/status"
      - "events"
      - "replicasets"
      - "configmaps"
      - "services"
      - "services/status"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-sandbox
subjects:
  - kind: ServiceAccount
    name: agent-sandbox
---

######################
#Deployment
######################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-sandbox
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-sandbox
  template:
    metadata:
      labels:
        app: agent-sandbox
    spec:
      serviceAccountName: agent-sandbox
      containers:
        - env:
            - name: KUBERNETES_MIN_VERSION
              value: "1.24.4-tke.26"
            - name: SANDBOX_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 10000
              scheme: HTTP
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 3
          name: agent-sandbox
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 10000
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
---

######################
#Service
######################
apiVersion: v1
kind: Service
metadata:
  name: agent-sandbox
  namespace: ${NS}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 10000
  selector:
    app: agent-sandbox
  type: ClusterIP
---

